### PR TITLE
Add Linux ARM64 binaries to build and release process

### PR DESCRIPTION
**Pull request by GUI**
This adds arm64 binaries into the build process for use on ARM64 Linux machines. I've tested running `make linux` locally, and that successfully builds for all 3 linux variants now. I've added it to the `make release-build` task too, so I believe (if I've traced things correctly), then this should mean the next tagged release in GitHub would automatically have arm64 binaries published in GitHub Releases too. Thanks!

### CODE REVIEW

**Comment by atc0005** [comment]
@GUI Thank you for taking the time to craft & submit the changes in this PR.

If you have a moment, I'd like to know more about the platforms/environments where you use the tools from this project:

- https://github.com/atc0005/check-cert/discussions/770

Since this project doesn't employ telemetry I don't have visibility into where or how the tools are used. I've considered adding builds for other platforms but wasn't sure if there was real demand for them.

I'll review/test the changes from this PR and provide feedback.

**Review by atc0005 — CHANGES_REQUESTED** [review]
The changes look functionally solid but some of the labels visible in the Makefile "menu" listing are incorrect. I've noted the ones I spotted while manually reviewing the changes.

Thanks again for taking the time to craft & submit this PR.

**Comment by atc0005** [comment]
> @GUI: I've added it to the make release-build task too, so I believe (if I've traced things correctly), then this should mean the next tagged release in GitHub would automatically have arm64 binaries published in GitHub Releases too.

I believe you are correct.

For better or worse the build process has quite a few layers. I optimized for reuse across multiple projects that I'm maintaining at the expense of some clarity. I'm hoping to refactor & simplify in the future.

As you've noted the next tagged release should generate additional assets. The entry point ends up being `make podman-release-build` per this imported workflow:

- https://github.com/atc0005/shared-project-resources/blob/0b6e0b7cf421e9914023805484e3f2f3a2cc34c1/.github/workflows/release-build.yml#L141-L143

and as you've noted ends up calling `make release-build`:

https://github.com/atc0005/check-cert/blob/d0555e276c225e01fefe8003c7f78defc672c7df/Makefile#L839

**Comment by GUI** [comment]
@atc0005: Doh! Sorry I missed so many of those, but thanks for taking a look and pointing all of this out! I've [pushed](https://github.com/atc0005/check-cert/compare/cfade5130941820d80aca2a414f327ba5fa81d71..4df5a9b2906baafe8496d4d105579b7309706a3b) up a change that I think addresses all of these (and I spotted one more). Let me know if you spot any other issues. Thanks!

**Comment by atc0005** [comment]
@GUI Thanks, I've not spotted any others.

Could you rebase on current master and force-push your branch? This should unstick CI checks.

**Comment by GUI** [comment]
Should be rebased with master now.

**Review by atc0005 — APPROVED** [review]

**Comment by atc0005** [comment]
@GUI Thanks for all of your work on this!

**Pull request merged**
